// Do not edit. This file is machine generated by the Resource DLL Wizard.

library MyEngine;

{ITE} {DFMFileType} {me_FuelTank.dfm}
{ITE} {DFMFileType} {me_MainForm.dfm}
{ITE} {DFMFileType} {me_Reset.dfm}
{ITE} {DFMFileType} {me_SelectView.dfm}
{ITE} {DFMFileType} {me_Settings.dfm}
{ITE} {DFMFileType} {me_Warning.dfm}
{ITE} {RCFileType} {MyEngine_DRC.rc}

{$R 'me_FuelTank.dfm' fmFuelTank:TForm}
{$R 'me_MainForm.dfm' fmMainForm:TForm}
{$R 'me_Reset.dfm' fmReset:TForm}
{$R 'me_SelectView.dfm' fmSelectView:TForm}
{$R 'me_Settings.dfm' fmSettings:TForm}
{$R 'me_Warning.dfm' fmWarning:TForm}
{$R 'MyEngine_DRC.res' 'MyEngine_DRC.rc'}

{$E ENG}

begin
end.